name: GB Redis Setup PHP

on: [workflow_dispatch, push, pull_request]

jobs:
  run:
    uses: flarum/framework/.github/workflows/REUSABLE_backend.yml@1.x
    with:
      enable_backend_testing: false
      enable_phpstan: false
      php_versions: '["7.4", "8.0", "8.1", "8.2", "8.3"]'

      backend_directory: .

    secrets:
      composer_auth: '{"bearer":{"extiverse.com": "${{secrets.EXTIVERSE_COMPOSER_TOKEN}}"}}'
